const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Appointment = sequelize.define('Appointment', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },

    customerId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },

    staffId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },

    serviceId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },

    // Service price frozen at booking time (column added by
    // migrations/001_payment_hardening.sql). Payments and invoices must use
    // this, never the live Service.price, which an admin can change later.
    servicePrice: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: true,
    },

    date: {
      type: DataTypes.DATEONLY,
      allowNull: false,
    },

    startTime: {
      type: DataTypes.STRING,
      allowNull: false,
    },

    endTime: {
      type: DataTypes.STRING,
      allowNull: false,
    },

    status: {
      type: DataTypes.ENUM(
        'booked',
        'completed',
        'cancelled',
        'rescheduled'
      ),
      allowNull: false,
      defaultValue: 'booked',
    },

    paymentStatus: {
      type: DataTypes.ENUM(
        'unpaid',
        'paid',
        'refunded'
      ),
      allowNull: false,
      defaultValue: 'unpaid',
    },

    rescheduleCount: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },

    // One-time proof-of-service code generated by the customer and verified by assigned staff.
    completionCode: {
      type: DataTypes.STRING(6),
      allowNull: true,
    },

    completionCodeGeneratedAt: {
      type: DataTypes.DATE,
      allowNull: true,
    },

    completionCodeUsedAt: {
      type: DataTypes.DATE,
      allowNull: true,
    },

  }, {
    tableName: 'appointments',
    timestamps: true,

  });

  return Appointment;
};